# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180606_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
