# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180606_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='update',
            new_name='updated',
        ),
    ]
