# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(max_length=60, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
